import { useEffect, useMemo, useState } from 'react';
import { api, getApiMessage } from '../api/client.js';
import { useAuth } from '../context/AuthContext.jsx';
import { normalizeRole } from '../access/roleAccess.js';
import { exportReport, getReportMetadata } from '../utils/reportExport.js';

const MODULES = [
  ['documents', '201 Files'],
  ['organization', 'Org Setup'],
  ['payroll', 'Payroll Extras'],
  ['loan', 'Loan Deductions'],
  ['compliance', 'Compliance'],
  ['leave', 'Company Calendar'],
  ['performance', 'Performance'],
  ['reports', 'Report Builder'],
  ['security', 'Security'],
  ['analytics', 'Analytics']
];

const GOVERNMENT_REPORTS = [
  ['BIR 1601-C', 'Monthly remittance return for compensation withholding tax', '10th of following month'],
  ['BIR 2316', 'Employee certificate of compensation payment and tax withheld', 'January 31'],
  ['BIR 1604-C', 'Annual information return for taxes withheld on compensation', 'Annual'],
  ['BIR Alphalist', 'Employee compensation details for eAFS submission', 'January 31'],
  ['SSS R3/R5', 'Contribution list and collection report', 'Monthly'],
  ['PhilHealth RF-1', 'Employer premium remittance report', 'Monthly'],
  ['Pag-IBIG MCRF', 'Monthly contribution remittance form', 'Monthly']
];

const PERMISSIONS = [
  'Employee master file',
  'Attendance adjustments',
  'Leave approvals',
  'Payroll computation',
  'Payslip release',
  'Government reports',
  'Utilities and tables',
  'Audit logs'
];

const PAYROLL_PROCESSING_SCOPE = [
  ['Gross Pay Calculation', 'Basic + OT + Allowances + Holiday Pay'],
  ['Statutory Deductions', 'SSS, PhilHealth, Pag-IBIG contributions'],
  ['Withholding Tax', 'BIR RR No. 11-2018, TRAIN Law rates'],
  ['Other Deductions', 'Loans, absences, late penalties'],
  ['Net Pay Computation', 'Gross pay - total deductions'],
  ['13th Month Pay', 'Automated annual computation']
];

const WEEKDAY_NAMES = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

function money(value) {
  return Number(value || 0).toLocaleString('en-PH', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2
  });
}

function escapeCsv(value) {
  const text = String(value ?? '');
  const safe = /^[=+\-@]/.test(text) ? `'${text}` : text;
  if (safe.includes(',') || safe.includes('"') || safe.includes('\n')) {
    return `"${safe.replace(/"/g, '""')}"`;
  }
  return safe;
}

function titleFromFilename(filename) {
  return String(filename || 'Report')
    .replace(/\.[^.]+$/, '')
    .replace(/[-_]+/g, ' ')
    .trim() || 'Report';
}

function buildCsvReport(title, headers, rows) {
  const meta = getReportMetadata(title);
  const line = (values) => values.map(escapeCsv).join(',');
  return [
    line([meta.companyName]),
    line([meta.title]),
    line(['Generated', meta.generatedAt]),
    line(['Generated By', meta.generatedBy]),
    '',
    [headers, ...rows]
      .map((row) => row.map(escapeCsv).join(','))
      .join('\n'),
    '',
    ...meta.signatories.map((label) => line([label]))
  ].join('\n');
}

function wrapCsvTextReport(title, csvText) {
  const meta = getReportMetadata(title);
  const line = (values) => values.map(escapeCsv).join(',');
  return [
    line([meta.companyName]),
    line([meta.title]),
    line(['Generated', meta.generatedAt]),
    line(['Generated By', meta.generatedBy]),
    '',
    String(csvText || '').replace(/^\ufeff/, '').trimEnd(),
    '',
    ...meta.signatories.map((label) => line([label]))
  ].join('\n');
}

function downloadCsv(filename, headers, rows, title = titleFromFilename(filename)) {
  const csv = buildCsvReport(title, headers, rows);
  const blob = new Blob([`\ufeff${csv}`], { type: 'text/csv;charset=utf-8;' });

  // IE / old Edge
  if (window.navigator && window.navigator.msSaveOrOpenBlob) {
    window.navigator.msSaveOrOpenBlob(blob, filename);
    return;
  }

  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.rel = 'noopener';
  link.style.display = 'none';
  document.body.appendChild(link);
  link.click();
  link.remove();
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

async function downloadFromApi(pathname, suggestedFilename = 'export.csv') {
  const response = await fetch(pathname, { credentials: 'include' });
  if (!response.ok) {
    let message = `Request failed (${response.status})`;
    try {
      const data = await response.json();
      message = data?.message || message;
    } catch {
      // ignore
    }
    throw new Error(message);
  }

  const disposition = response.headers.get('content-disposition') || '';
  const match = disposition.match(/filename="([^"]+)"/i);
  const filename = match?.[1] || suggestedFilename;
  const contentType = response.headers.get('content-type') || '';
  const isCsv = /\.csv$/i.test(filename) || contentType.toLowerCase().includes('csv');
  const blob = isCsv
    ? new Blob([`\ufeff${wrapCsvTextReport(titleFromFilename(filename), await response.text())}`], { type: 'text/csv;charset=utf-8;' })
    : await response.blob();

  // IE / old Edge
  if (window.navigator && window.navigator.msSaveOrOpenBlob) {
    window.navigator.msSaveOrOpenBlob(blob, filename);
    return;
  }

  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.rel = 'noopener';
  link.style.display = 'none';
  document.body.appendChild(link);
  link.click();
  link.remove();
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

export default function AdvancedModulesPage({ moduleKey: forcedModuleKey = '' }) {
  const allowedModules = useMemo(() => new Set(MODULES.map(([key]) => key)), []);
  const initialModule = allowedModules.has(forcedModuleKey) ? forcedModuleKey : 'documents';
  const [activeModule, setActiveModule] = useState(initialModule);

  useEffect(() => {
    const nextModule = allowedModules.has(forcedModuleKey) ? forcedModuleKey : 'documents';
    setActiveModule(nextModule);
  }, [allowedModules, forcedModuleKey]);

  return (
    <>
      <header className="header">
        <h2>Advanced Modules</h2>
        <p>Additional HRIS, payroll, compliance, security, analytics, and reporting modules from the project workbook.</p>
      </header>

      {activeModule === 'documents' ? <DocumentManagement /> : null}
      {activeModule === 'organization' ? <OrganizationSetup /> : null}
      {activeModule === 'payroll' ? <PayrollExtras /> : null}
      {activeModule === 'loan' ? <LoanDeductions /> : null}
      {activeModule === 'compliance' ? <ComplianceReports /> : null}
      {activeModule === 'leave' ? <CompanyCalendar /> : null}
      {activeModule === 'performance' ? <PerformanceManagement /> : null}
      {activeModule === 'reports' ? <CustomReportBuilder /> : null}
      {activeModule === 'security' ? <SecurityCenter /> : null}
      {activeModule === 'analytics' ? <AnalyticsAndMobile /> : null}
    </>
  );
}

function DocumentManagement() {
  const [rows, setRows] = useState([
    { employee: 'EMP-001', document: 'Employment Contract', type: 'Contract', status: 'Complete', expiry: '' },
    { employee: 'EMP-002', document: 'TIN / SSS / PhilHealth / Pag-IBIG', type: 'Government ID', status: 'For Review', expiry: '' }
  ]);
  const [form, setForm] = useState({ employee: '', document: '', type: '201 File', status: 'Pending', expiry: '' });

  function addRow() {
    if (!form.employee.trim() || !form.document.trim()) return;
    setRows((current) => [...current, form]);
    setForm({ employee: '', document: '', type: '201 File', status: 'Pending', expiry: '' });
  }

  return (
    <section className="table-section">
      <h3>Employee 201 File Tracker</h3>
      <div className="report-filter-grid">
        <label>Employee ID<input value={form.employee} onChange={(event) => setForm((current) => ({ ...current, employee: event.target.value }))} /></label>
        <label>Document<input value={form.document} onChange={(event) => setForm((current) => ({ ...current, document: event.target.value }))} /></label>
        <label>Type<select value={form.type} onChange={(event) => setForm((current) => ({ ...current, type: event.target.value }))}><option>201 File</option><option>Contract</option><option>Certificate</option><option>Government ID</option><option>Clearance</option></select></label>
        <label>Status<select value={form.status} onChange={(event) => setForm((current) => ({ ...current, status: event.target.value }))}><option>Pending</option><option>For Review</option><option>Complete</option><option>Expired</option></select></label>
        <label>Expiry<input type="date" value={form.expiry} onChange={(event) => setForm((current) => ({ ...current, expiry: event.target.value }))} /></label>
        <div className="toolbar"><button type="button" className="btn" onClick={addRow}>Add Document</button></div>
      </div>
      <SimpleTable headers={['Employee', 'Document', 'Type', 'Status', 'Expiry']} rows={rows.map((row) => [row.employee, row.document, row.type, row.status, row.expiry || '-'])} />
    </section>
  );
}

function OrganizationSetup() {
  const [employees, setEmployees] = useState([]);
  const [loading,   setLoading]   = useState(true);
  const [error,     setError]     = useState('');
  const [search,    setSearch]    = useState('');
  const [view,      setView]      = useState('department');
  const [selected,  setSelected]  = useState(null);

  // Designation Management
  const [designations, setDesignations] = useState([]);
  const [desgForm, setDesgForm] = useState({ title: '', description: '', salary_grade: '', department: '' });
  const [desgSearch, setDesgSearch] = useState('');
  const [editDesgIdx, setEditDesgIdx] = useState(null);

  useEffect(() => {
    api.get('/employees')
      .then(({ data }) => {
        const emps = data.employees || [];
        setEmployees(emps);
        // Seed designations from existing positions (deduplicated)
        setDesignations((prev) => {
          if (prev.length > 0) return prev;
          const seen = new Set();
          return emps
            .filter((e) => e.position && !seen.has(e.position) && seen.add(e.position))
            .map((e) => ({ title: e.position, description: '', salary_grade: '', department: e.department || '' }));
        });
      })
      .catch((err) => setError(getApiMessage(err, 'Failed to load employees.')))
      .finally(() => setLoading(false));
  }, []);

  const totalEmployees  = employees.length;
  const activeEmployees = useMemo(() => employees.filter((e) => (e.status || '').toLowerCase() === 'active').length, [employees]);
  const totalDepts      = useMemo(() => new Set(employees.map((e) => e.department).filter(Boolean)).size, [employees]);
  const totalPositions  = useMemo(() => new Set(employees.map((e) => e.position).filter(Boolean)).size, [employees]);

  // Build org-unit summary rows for the current view
  const orgUnits = useMemo(() => {
    const grouped = employees.reduce((acc, emp) => {
      const key = emp[view] || 'Unassigned';
      if (!acc[key]) acc[key] = [];
      acc[key].push(emp);
      return acc;
    }, {});
    return Object.entries(grouped)
      .map(([name, members]) => ({
        name,
        total:     members.length,
        active:    members.filter((e) => (e.status || '').toLowerCase() === 'active').length,
        positions: new Set(members.map((e) => e.position).filter(Boolean)).size,
        members,
      }))
      .sort((a, b) => {
        if (a.name === 'Unassigned') return 1;
        if (b.name === 'Unassigned') return -1;
        return a.name.localeCompare(b.name);
      });
  }, [employees, view]);

  const q = search.toLowerCase().trim();
  const filteredUnits = q
    ? orgUnits.filter((u) =>
        u.name.toLowerCase().includes(q) ||
        u.members.some((e) =>
          `${e.first_name} ${e.last_name}`.toLowerCase().includes(q) ||
          (e.emp_code || '').toLowerCase().includes(q)
        )
      )
    : orgUnits;

  const selectedUnit = orgUnits.find((u) => u.name === selected) || null;

  function switchView(field) {
    setView(field);
    setSelected(null);
    setSearch('');
  }

  const VIEWS = [
    { key: 'department', label: 'Department' },
    { key: 'division',   label: 'Division'   },
    { key: 'company',    label: 'Company'    },
  ];

  const unitLabel = view === 'department' ? 'Department' : view === 'division' ? 'Division' : 'Company';

  return (
    <>
      {/* ── Summary cards ── */}
      <section className="summary react-summary">
        <div className="card"><span>Total Employees</span><strong>{totalEmployees}</strong></div>
        <div className="card"><span>Active</span><strong>{activeEmployees}</strong></div>
        <div className="card"><span>Departments</span><strong>{totalDepts}</strong></div>
        <div className="card"><span>Unique Positions</span><strong>{totalPositions}</strong></div>
      </section>

      {/* ── Org unit table ── */}
      <section className="table-section">
        <div className="table-header">
          <div>
            <h3>Organization Structure</h3>
            <p>Select a {unitLabel.toLowerCase()} to view its employees.</p>
          </div>
          <div className="toolbar">
            {VIEWS.map((v) => (
              <button
                key={v.key}
                type="button"
                className={view === v.key ? 'btn' : 'btn secondary'}
                onClick={() => switchView(v.key)}
              >
                {v.label}
              </button>
            ))}
            <input
              type="text"
              placeholder={`Search ${unitLabel.toLowerCase()}…`}
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              style={{ padding: '6px 10px', borderRadius: '6px', border: '1px solid #e2e8f0', fontSize: '13px', minWidth: '160px' }}
            />
          </div>
        </div>

        {loading && <p style={{ color: '#64748b', padding: '16px 0' }}>Loading…</p>}
        {error   && <p className="message">{error}</p>}

        {!loading && !error && (
          <table>
            <thead>
              <tr>
                <th>{unitLabel}</th>
                <th>Total</th>
                <th>Active</th>
                <th>Inactive</th>
                <th>Unique Positions</th>
              </tr>
            </thead>
            <tbody>
              {filteredUnits.map((unit) => (
                <tr
                  key={unit.name}
                  onClick={() => setSelected(selected === unit.name ? null : unit.name)}
                  style={{ cursor: 'pointer', background: selected === unit.name ? '#eff6ff' : undefined, fontWeight: selected === unit.name ? 600 : undefined }}
                >
                  <td>{unit.name}</td>
                  <td>{unit.total}</td>
                  <td><span className="status active">{unit.active}</span></td>
                  <td>{unit.total - unit.active}</td>
                  <td>{unit.positions}</td>
                </tr>
              ))}
              {filteredUnits.length === 0 && (
                <tr><td colSpan={5} style={{ textAlign: 'center', color: '#94a3b8' }}>No results found.</td></tr>
              )}
            </tbody>
          </table>
        )}
      </section>

      {/* ── Employee detail for selected unit ── */}
      {selectedUnit && (
        <section className="table-section">
          <div className="table-header">
            <div>
              <h3>{selectedUnit.name}</h3>
              <p>{selectedUnit.total} employees &middot; {selectedUnit.active} active</p>
            </div>
            <div className="toolbar">
              <button type="button" className="btn secondary" onClick={() => setSelected(null)}>Close</button>
            </div>
          </div>
          <table>
            <thead>
              <tr>
                <th>Employee</th>
                <th>ID</th>
                {view === 'company'   && <th>Division</th>}
                {view !== 'department' && <th>Department</th>}
                <th>Position</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {selectedUnit.members.map((emp) => (
                <tr key={emp.employee_id || emp.emp_code}>
                  <td>{emp.first_name} {emp.last_name}</td>
                  <td>{emp.emp_code || '-'}</td>
                  {view === 'company'    && <td>{emp.division   || '-'}</td>}
                  {view !== 'department' && <td>{emp.department || '-'}</td>}
                  <td>{emp.position || '-'}</td>
                  <td><span className={`status ${(emp.status || 'active').toLowerCase()}`}>{emp.status || 'Active'}</span></td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      )}

      {/* ── Designation Management ── */}
      <section className="table-section">
        <div className="table-header">
          <div>
            <h3>Designation Management</h3>
            <p>Manage job titles, define responsibilities, and link to salary grade structures.</p>
          </div>
          <div className="toolbar">
            <input
              type="text"
              placeholder="Search designation…"
              value={desgSearch}
              onChange={(e) => setDesgSearch(e.target.value)}
              style={{ padding: '6px 10px', borderRadius: '6px', border: '1px solid #e2e8f0', fontSize: '13px', minWidth: '160px' }}
            />
          </div>
        </div>

        {/* Form — add or edit */}
        <div className="report-filter-grid" style={{ marginBottom: 12 }}>
          <label>
            Job Title
            <input
              placeholder="e.g. Payroll Specialist"
              value={desgForm.title}
              onChange={(e) => setDesgForm((f) => ({ ...f, title: e.target.value }))}
            />
          </label>
          <label>
            Department
            <select
              value={desgForm.department}
              onChange={(e) => setDesgForm((f) => ({ ...f, department: e.target.value }))}
            >
              <option value="">— Select department —</option>
              {[...new Set(employees.map((e) => e.department).filter(Boolean))].sort().map((d) => (
                <option key={d} value={d}>{d}</option>
              ))}
            </select>
          </label>
          <label>
            Salary Grade
            <input
              placeholder="e.g. SG-10"
              value={desgForm.salary_grade}
              onChange={(e) => setDesgForm((f) => ({ ...f, salary_grade: e.target.value }))}
            />
          </label>
          <label>
            Job Description / Responsibilities
            <input
              placeholder="Brief description of responsibilities"
              value={desgForm.description}
              onChange={(e) => setDesgForm((f) => ({ ...f, description: e.target.value }))}
            />
          </label>
          <div className="toolbar">
            <button
              type="button"
              className="btn"
              onClick={() => {
                if (!desgForm.title.trim()) return;
                if (editDesgIdx !== null) {
                  setDesignations((prev) => prev.map((d, i) => i === editDesgIdx ? { ...desgForm } : d));
                  setEditDesgIdx(null);
                } else {
                  setDesignations((prev) => [...prev, { ...desgForm }]);
                }
                setDesgForm({ title: '', description: '', salary_grade: '', department: '' });
              }}
            >
              {editDesgIdx !== null ? 'Update' : 'Add Designation'}
            </button>
            {editDesgIdx !== null && (
              <button
                type="button"
                className="btn secondary"
                onClick={() => { setEditDesgIdx(null); setDesgForm({ title: '', description: '', salary_grade: '', department: '' }); }}
              >
                Cancel
              </button>
            )}
          </div>
        </div>

        {/* Designations table */}
        <table>
          <thead>
            <tr>
              <th>Job Title</th>
              <th>Department</th>
              <th>Job Description / Responsibilities</th>
              <th>Salary Grade</th>
              <th>Headcount</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {designations
              .filter((d) => !desgSearch || d.title.toLowerCase().includes(desgSearch.toLowerCase()) || (d.department || '').toLowerCase().includes(desgSearch.toLowerCase()))
              .map((d, i) => {
                const headcount = employees.filter((e) => (e.position || '').toLowerCase() === d.title.toLowerCase()).length;
                return (
                  <tr key={i}>
                    <td><strong>{d.title}</strong></td>
                    <td>{d.department || '-'}</td>
                    <td style={{ color: d.description ? '#0f172a' : '#94a3b8' }}>{d.description || 'No description set'}</td>
                    <td>{d.salary_grade ? <span className="status approved">{d.salary_grade}</span> : <span style={{ color: '#94a3b8' }}>—</span>}</td>
                    <td>{headcount}</td>
                    <td>
                      <div className="toolbar" style={{ gap: 6 }}>
                        <button
                          type="button"
                          className="btn secondary"
                          style={{ padding: '3px 10px', fontSize: 12 }}
                          onClick={() => { setDesgForm({ ...d }); setEditDesgIdx(i); }}
                        >
                          Edit
                        </button>
                        <button
                          type="button"
                          className="btn secondary"
                          style={{ padding: '3px 10px', fontSize: 12, color: '#dc2626' }}
                          onClick={() => setDesignations((prev) => prev.filter((_, idx) => idx !== i))}
                        >
                          Remove
                        </button>
                      </div>
                    </td>
                  </tr>
                );
              })}
            {designations.length === 0 && (
              <tr><td colSpan={6} style={{ textAlign: 'center', color: '#94a3b8' }}>No designations added yet.</td></tr>
            )}
          </tbody>
        </table>
      </section>
    </>
  );
}

function PayrollExtras() {
  const [payroll, setPayroll] = useState({
    basic: 30000,
    months: 12,
    absences: 0,
    taxable: 50000,
    withheld: 4800,
    loan: 25000,
    terms: 10,
    nightHours: 8,
    hourlyRate: 180,
    premiumRate: 10
  });

  const thirteenthMonth = Math.max(0, (Number(payroll.basic) * Number(payroll.months)) / 12 - Number(payroll.absences || 0));
  const loanAmortization = Number(payroll.terms || 0) > 0 ? Number(payroll.loan || 0) / Number(payroll.terms || 1) : 0;
  const nightDiff = Number(payroll.nightHours || 0) * Number(payroll.hourlyRate || 0) * (Number(payroll.premiumRate || 0) / 100);
  const annualTaxDue = computeMonthlyTax(Number(payroll.taxable || 0));
  const annualizationDelta = annualTaxDue - Number(payroll.withheld || 0);

  function update(field, value) {
    setPayroll((current) => ({ ...current, [field]: value }));
  }

  return (
    <>
      <section className="summary react-summary">
        <div className="card"><span>13th Month Estimate</span><strong>PHP {money(thirteenthMonth)}</strong></div>
        <div className="card"><span>Loan Amortization</span><strong>PHP {money(loanAmortization)}</strong></div>
        <div className="card"><span>Night Diff Premium</span><strong>PHP {money(nightDiff)}</strong></div>
        <div className="card"><span>Tax Refund / Payable</span><strong>PHP {money(Math.abs(annualizationDelta))}</strong></div>
      </section>
      <section className="table-section">
        <div className="table-header">
          <div>
            <h3>Payroll Processing</h3>
            <p>Automated salary computation for gross pay, deductions, tax, net pay, and annual 13th month pay.</p>
          </div>
        </div>
        <SimpleTable
          headers={['No.', 'Module', 'Feature', 'Computation / Basis']}
          rows={PAYROLL_PROCESSING_SCOPE.map(([feature, basis], index) => [
            index === 0 ? '8' : '',
            index === 0 ? 'Payroll Processing' : '',
            feature,
            basis
          ])}
        />
      </section>
      <section className="table-section">
        <h3>13th Month, Loans, Night Differential, and Tax Annualization</h3>
        <div className="report-filter-grid">
          <label>Monthly Basic<input type="number" value={payroll.basic} onChange={(event) => update('basic', event.target.value)} /></label>
          <label>Months Worked<input type="number" value={payroll.months} onChange={(event) => update('months', event.target.value)} /></label>
          <label>Absence Adjustments<input type="number" value={payroll.absences} onChange={(event) => update('absences', event.target.value)} /></label>
          <label>Monthly Taxable Income<input type="number" value={payroll.taxable} onChange={(event) => update('taxable', event.target.value)} /></label>
          <label>Tax Already Withheld<input type="number" value={payroll.withheld} onChange={(event) => update('withheld', event.target.value)} /></label>
          <label>Loan Balance<input type="number" value={payroll.loan} onChange={(event) => update('loan', event.target.value)} /></label>
          <label>Loan Terms<input type="number" value={payroll.terms} onChange={(event) => update('terms', event.target.value)} /></label>
          <label>Night Hours<input type="number" value={payroll.nightHours} onChange={(event) => update('nightHours', event.target.value)} /></label>
          <label>Hourly Rate<input type="number" value={payroll.hourlyRate} onChange={(event) => update('hourlyRate', event.target.value)} /></label>
          <label>Premium Rate %<input type="number" value={payroll.premiumRate} onChange={(event) => update('premiumRate', event.target.value)} /></label>
        </div>
        <p className="muted">Tax uses the monthly TRAIN table from the workbook. Negative delta means estimated refund; positive delta means additional payable.</p>
      </section>
    </>
  );
}

function LoanDeductions() {
  const [loan, setLoan] = useState({
    category: 'Company Loan',
    balance: 25000,
    terms: 10,
    amortization: 2500,
    payrollDeduction: 2500
  });

  function update(field, value) {
    setLoan((current) => ({ ...current, [field]: value }));
  }

  const amortization = Number(loan.amortization || 0) || (Number(loan.balance || 0) / Math.max(1, Number(loan.terms || 1)));
  const remainingBalance = Math.max(0, Number(loan.balance || 0) - Number(loan.payrollDeduction || 0));

  return (
    <>
      <section className="summary react-summary">
        <div className="card"><span>Loan Balance</span><strong>PHP {money(loan.balance)}</strong></div>
        <div className="card"><span>Amortization</span><strong>PHP {money(amortization)}</strong></div>
        <div className="card"><span>Estimated Payroll Deduction</span><strong>PHP {money(loan.payrollDeduction)}</strong></div>
        <div className="card"><span>Balance After Deduction</span><strong>PHP {money(remainingBalance)}</strong></div>
      </section>
      <section className="table-section">
        <h3>Loan Deduction Module</h3>
        <div className="report-filter-grid">
          <label>Category
            <select value={loan.category} onChange={(event) => update('category', event.target.value)}>
              <option>Company Loan</option>
              <option>SSS Loan</option>
              <option>Pag-IBIG Loan</option>
            </select>
          </label>
          <label>Loan Balance<input type="number" value={loan.balance} onChange={(event) => update('balance', event.target.value)} /></label>
          <label>Terms<input type="number" value={loan.terms} onChange={(event) => update('terms', event.target.value)} /></label>
          <label>Amortization<input type="number" value={loan.amortization} onChange={(event) => update('amortization', event.target.value)} /></label>
          <label>Payroll Deduction<input type="number" value={loan.payrollDeduction} onChange={(event) => update('payrollDeduction', event.target.value)} /></label>
        </div>
        <p className="muted">Use this module to estimate loan deductions and remaining balances for company, SSS, and Pag-IBIG loans.</p>
      </section>
    </>
  );
}

function computeMonthlyTax(taxableIncome) {
  if (taxableIncome <= 20833) return 0;
  if (taxableIncome <= 33332) return (taxableIncome - 20833) * 0.15;
  if (taxableIncome <= 66666) return 1875 + (taxableIncome - 33333) * 0.2;
  if (taxableIncome <= 166666) return 8541.8 + (taxableIncome - 66667) * 0.25;
  if (taxableIncome <= 666666) return 33541.8 + (taxableIncome - 166667) * 0.3;
  return 183541.8 + (taxableIncome - 666667) * 0.35;
}

function ComplianceReports() {
  const [year, setYear] = useState(() => new Date().getFullYear());
  const [month, setMonth] = useState(() => new Date().getMonth() + 1);
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);
  const [runs, setRuns] = useState([]);
  const [filters, setFilters] = useState({ companies: [], departments: [] });
  const [fromRunId, setFromRunId] = useState('');
  const [toRunId, setToRunId] = useState('');
  const [transaction, setTransaction] = useState('active');
  const [excludeZero, setExcludeZero] = useState(true);
  const [company, setCompany] = useState('');
  const [department, setDepartment] = useState('');

  useEffect(() => {
    let alive = true;

    (async () => {
      try {
        const response = await fetch('/api/government-reports/sss/options', { credentials: 'include' });
        const data = await response.json();
        if (!alive) return;
        if (response.ok && data?.success) {
          setRuns(Array.isArray(data.runs) ? data.runs : []);
          setFilters(data.filters || { companies: [], departments: [] });
        }
      } catch {
        // ignore
      }
    })();

    return () => {
      alive = false;
    };
  }, []);

  function exportReports() {
    downloadCsv('government-report-checklist.csv', ['Report', 'Purpose', 'Deadline'], GOVERNMENT_REPORTS);
  }

  async function exportSssCollection() {
    setBusy(true);
    setMessage('');

    try {
      if (!fromRunId || !toRunId) {
        throw new Error('Please select From and To payroll runs.');
      }

      const params = new URLSearchParams({
        from_run_id: String(fromRunId),
        to_run_id: String(toRunId),
        transaction,
        exclude_zero: excludeZero ? '1' : '0'
      });
      if (company) params.set('company', company);
      if (department) params.set('department', department);

      await downloadFromApi(`/api/government-reports/sss-collection?${params.toString()}`, `SSS-Collection-${fromRunId}-to-${toRunId}.csv`);
      setMessage('SSS report exported.');
    } catch (err) {
      setMessage(err?.message || 'Unable to export SSS report.');
    } finally {
      setBusy(false);
    }
  }

  async function exportAll() {
    setBusy(true);
    setMessage('');

    try {
      const monthPad = String(month).padStart(2, '0');
      await downloadFromApi(`/api/government-reports/bir-1601c?year=${year}&month=${month}`, `BIR-1601C-${year}-${monthPad}.csv`);
      await downloadFromApi(`/api/government-reports/sss?year=${year}&month=${month}`, `SSS-R3-R5-${year}-${monthPad}.csv`);
      await downloadFromApi(`/api/government-reports/philhealth?year=${year}&month=${month}`, `PhilHealth-RF1-${year}-${monthPad}.csv`);
      await downloadFromApi(`/api/government-reports/pagibig?year=${year}&month=${month}`, `PagIBIG-MCRF-${year}-${monthPad}.csv`);
      await downloadFromApi(`/api/government-reports/bir-2316?year=${year}`, `BIR-2316-${year}.csv`);
      await downloadFromApi(`/api/government-reports/bir-1604c?year=${year}`, `BIR-1604C-${year}.csv`);
      await downloadFromApi(`/api/government-reports/bir-alphalist?year=${year}`, `BIR-Alphalist-${year}.csv`);
      setMessage('Exports generated.');
    } catch (err) {
      setMessage(err?.message || 'Unable to export reports.');
    } finally {
      setBusy(false);
    }
  }

  return (
    <section className="table-section">
      <div className="table-header">
        <div>
          <h3>Government Report Generators</h3>
          <p>BIR, SSS, PhilHealth, and Pag-IBIG report checklist and export templates.</p>
        </div>
        <div className="toolbar">
          <label>Year<input type="number" min="1990" max="2100" value={year} onChange={(event) => setYear(Number(event.target.value || 0))} /></label>
          <label>Month<input type="number" min="1" max="12" value={month} onChange={(event) => setMonth(Number(event.target.value || 0))} /></label>
          <button type="button" className="btn secondary" onClick={exportReports}>Export Checklist</button>
          <button type="button" className="btn" onClick={exportAll} disabled={busy}>{busy ? 'Exporting…' : 'Export All CSV'}</button>
        </div>
      </div>
      <SimpleTable headers={['Report', 'Purpose', 'Deadline']} rows={GOVERNMENT_REPORTS} />

      <div className="card" style={{ marginTop: 16 }}>
        <h4 style={{ marginTop: 0 }}>SSS Contribution Collection List (R-3/R-5)</h4>
        <div className="report-filter-grid">
          <label>
            From Run
            <select value={fromRunId} onChange={(event) => setFromRunId(event.target.value)}>
              <option value="">Select</option>
              {runs.map((run) => (
                <option key={run.run_id} value={run.run_id}>
                  {run.run_id} — {run.payroll_range || `${run.group_id} ${run.period_id} ${run.month_id}/${run.year_id}`}
                </option>
              ))}
            </select>
          </label>
          <label>
            To Run
            <select value={toRunId} onChange={(event) => setToRunId(event.target.value)}>
              <option value="">Select</option>
              {runs.map((run) => (
                <option key={run.run_id} value={run.run_id}>
                  {run.run_id} — {run.payroll_range || `${run.group_id} ${run.period_id} ${run.month_id}/${run.year_id}`}
                </option>
              ))}
            </select>
          </label>
          <label>
            Transaction
            <select value={transaction} onChange={(event) => setTransaction(event.target.value)}>
              <option value="all">All</option>
              <option value="active">Active</option>
              <option value="hold">Hold</option>
            </select>
          </label>
          <label>
            Company
            <select value={company} onChange={(event) => setCompany(event.target.value)}>
              <option value="">All</option>
              {filters.companies.map((value) => (
                <option key={value} value={value}>{value}</option>
              ))}
            </select>
          </label>
          <label>
            Department
            <select value={department} onChange={(event) => setDepartment(event.target.value)}>
              <option value="">All</option>
              {filters.departments.map((value) => (
                <option key={value} value={value}>{value}</option>
              ))}
            </select>
          </label>
          <label style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
            <input type="checkbox" checked={excludeZero} onChange={(event) => setExcludeZero(event.target.checked)} />
            Exclude ZERO contribution
          </label>
          <div className="toolbar">
            <button type="button" className="btn" onClick={exportSssCollection} disabled={busy}>
              {busy ? 'Exporting…' : 'Export SSS CSV'}
            </button>
          </div>
        </div>
      </div>

      {message ? <p className="message">{message}</p> : null}
    </section>
  );
}

function CompanyCalendar() {
  const { user } = useAuth();
  const role = normalizeRole(user?.role);
  const canManageCalendar = role === 'admin' || role === 'hr';
  const [month, setMonth] = useState(() => new Date().toISOString().slice(0, 7));
  const [events, setEvents] = useState([]);
  const [editingEventId, setEditingEventId] = useState(null);
  const [form, setForm] = useState({
    event_date: new Date().toISOString().slice(0, 10),
    title: '',
    event_type: 'Company Holiday',
    description: '',
    is_paid_holiday: true
  });
  const [message, setMessage] = useState('');
  const [loading, setLoading] = useState(false);
  const isHolidayEvent = (event) => /holiday|non-working/i.test(String(event.event_type || ''));

  const days = useMemo(() => {
    const [year, monthIndex] = month.split('-').map(Number);
    const count = new Date(year, monthIndex, 0).getDate();
    return Array.from({ length: count }, (_, index) => index + 1);
  }, [month]);
  const firstDayOffset = useMemo(() => {
    const [year, monthIndex] = month.split('-').map(Number);
    return new Date(year, monthIndex - 1, 1).getDay();
  }, [month]);
  const eventsByDay = useMemo(() => {
    return events.reduce((acc, event) => {
      const day = Number(String(event.event_date || '').slice(8, 10));
      if (!day) return acc;
      acc[day] = [...(acc[day] || []), event];
      return acc;
    }, {});
  }, [events]);
  const holidayCount = events.filter(isHolidayEvent).length;
  const paidHolidayCount = events.filter((event) => Number(event.is_paid_holiday) === 1).length;
  const payrollDeadlineCount = events.filter((event) => event.event_type === 'Payroll Deadline').length;

  async function loadEvents(targetMonth = month) {
    setLoading(true);
    setMessage('');

    try {
      const { data } = await api.get('/company-calendar/events', { params: { month: targetMonth } });
      if (!data.success) throw new Error(data.message || 'Unable to load company calendar.');
      setEvents(data.events || []);
    } catch (err) {
      setMessage(getApiMessage(err, 'Unable to load company calendar.'));
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadEvents(month).catch(() => {});
  }, [month]);

  function updateForm(field, value) {
    setForm((current) => ({ ...current, [field]: value }));
  }

  function startEdit(calEvent) {
    setEditingEventId(calEvent.event_id);
    setForm({
      event_date: calEvent.event_date,
      title: calEvent.title,
      event_type: calEvent.event_type,
      description: calEvent.description || '',
      is_paid_holiday: Number(calEvent.is_paid_holiday) === 1
    });
    setMessage(`Editing event: ${calEvent.title}`);
  }

  function cancelEdit() {
    setEditingEventId(null);
    setForm({
      event_date: new Date().toISOString().slice(0, 10),
      title: '',
      event_type: 'Company Holiday',
      description: '',
      is_paid_holiday: true
    });
    setMessage('');
  }

  async function saveEvent(event) {
    event.preventDefault();
    setLoading(true);
    setMessage('');

    try {
      const payload = {
        ...form,
        title: form.title.trim(),
        description: form.description.trim(),
        is_paid_holiday: form.is_paid_holiday ? 1 : 0
      };
      const { data } = editingEventId
        ? await api.put(`/company-calendar/events/${editingEventId}`, payload)
        : await api.post('/company-calendar/events', payload);
      if (!data.success) throw new Error(data.message || 'Unable to save calendar event.');
      cancelEdit();
      setMessage(editingEventId ? 'Calendar event updated.' : 'Calendar event added.');
      await loadEvents(month);
    } catch (err) {
      setMessage(getApiMessage(err, 'Unable to save calendar event.'));
    } finally {
      setLoading(false);
    }
  }

  async function deleteEvent(eventId) {
    setLoading(true);
    setMessage('');

    try {
      const { data } = await api.delete(`/company-calendar/events/${eventId}`);
      if (!data.success) throw new Error(data.message || 'Unable to delete calendar event.');
      setMessage('Calendar event deleted.');
      await loadEvents(month);
    } catch (err) {
      setMessage(getApiMessage(err, 'Unable to delete calendar event.'));
    } finally {
      setLoading(false);
    }
  }

  return (
    <>
      <section className="summary react-summary">
        <div className="card"><span>Calendar Items</span><strong>{events.length}</strong></div>
        <div className="card"><span>Company Holidays</span><strong>{holidayCount}</strong></div>
        <div className="card"><span>Paid Holidays</span><strong>{paidHolidayCount}</strong></div>
        <div className="card"><span>Payroll Deadlines</span><strong>{payrollDeadlineCount}</strong></div>
      </section>

      <section className="table-section">
        <div className="table-header">
          <div>
            <h3>Company Calendar</h3>
            <p>Track company holidays, special non-working days, payroll deadlines, and internal events.</p>
          </div>
          <input type="month" value={month} onChange={(event) => setMonth(event.target.value)} />
        </div>
        <div className="advanced-calendar">
          {WEEKDAY_NAMES.map((dayName) => (
            <div key={dayName} className="calendar-weekday">{dayName}</div>
          ))}
          {Array.from({ length: firstDayOffset }, (_, index) => (
            <div key={`blank-${index}`} className="calendar-blank" aria-hidden="true" />
          ))}
          {days.map((day) => {
            const dayEvents = eventsByDay[day] || [];
            const hasHoliday = dayEvents.some(isHolidayEvent);
            return (
              <div key={day} className={`calendar-day ${dayEvents.length ? (hasHoliday ? 'has-holiday' : 'has-event') : ''}`}>
                <strong>{day}</strong>
                {dayEvents.length ? (
                  <span>{dayEvents[0].event_type}</span>
                ) : (
                  <span>Open</span>
                )}
                {dayEvents.slice(0, 2).map((event) => (
                  <small key={event.event_id}>{event.title}</small>
                ))}
                {dayEvents.length > 2 ? <small>+{dayEvents.length - 2} more</small> : null}
              </div>
            );
          })}
        </div>
      </section>

      {canManageCalendar ? (
        <section className="table-section">
          <div className="table-header">
            <div>
              <h3>{editingEventId ? 'Edit Calendar Item' : 'Add Calendar Item'}</h3>
              <p>Use holidays for company-wide non-working dates and events for reminders or announcements.</p>
            </div>
          </div>
          <form className="report-filter-grid company-calendar-form" onSubmit={saveEvent}>
            <label>Date<input type="date" value={form.event_date} onChange={(event) => updateForm('event_date', event.target.value)} required /></label>
            <label>Title<input value={form.title} onChange={(event) => updateForm('title', event.target.value)} placeholder="Example: Independence Day" required /></label>
            <label>Type
              <select value={form.event_type} onChange={(event) => updateForm('event_type', event.target.value)}>
                <option>Company Holiday</option>
                <option>Special Non-Working Day</option>
                <option>Company Event</option>
                <option>Payroll Deadline</option>
                <option>Other</option>
              </select>
            </label>
            <label>Description<input value={form.description} onChange={(event) => updateForm('description', event.target.value)} placeholder="Optional notes" /></label>
            <label className="calendar-check">
              <input type="checkbox" checked={form.is_paid_holiday} onChange={(event) => updateForm('is_paid_holiday', event.target.checked)} />
              Paid holiday
            </label>
            <div className="toolbar">
              <button type="submit" className="btn" disabled={loading}>{loading ? 'Saving...' : editingEventId ? 'Update Item' : 'Add Item'}</button>
              {editingEventId ? <button type="button" className="btn secondary" onClick={cancelEdit}>Cancel</button> : null}
            </div>
          </form>
          {message ? <p className="message">{message}</p> : null}
        </section>
      ) : null}

      <section className="table-section">
        <h3>Calendar Items</h3>
        <div className="table-scroll">
          <table>
            <thead>
              <tr>
                <th>Date</th>
                {canManageCalendar ? <th>Actions</th> : null}
                <th>Title</th>
                <th>Type</th>
                <th>Paid</th>
                <th>Description</th>
              </tr>
            </thead>
            <tbody>
              {events.length === 0 ? <tr><td colSpan={canManageCalendar ? 6 : 5}>No calendar items for this month.</td></tr> : null}
              {events.map((event) => (
                <tr key={event.event_id}>
                  <td>{event.event_date}</td>
                  {canManageCalendar ? (
                    <td>
                      <div className="row-actions">
                        <button type="button" className="btn small-btn" disabled={loading} onClick={() => startEdit(event)}>Edit</button>
                        <button type="button" className="btn secondary small-btn" disabled={loading} onClick={() => deleteEvent(event.event_id)}>Delete</button>
                      </div>
                    </td>
                  ) : null}
                  <td>{event.title}</td>
                  <td><span className="status completed">{event.event_type}</span></td>
                  <td>{Number(event.is_paid_holiday) === 1 ? 'Yes' : 'No'}</td>
                  <td>{event.description || '-'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </>
  );
}

function PerformanceManagement() {
  const { user } = useAuth();
  const [evaluations, setEvaluations] = useState([]);
  const [summary, setSummary] = useState({});
  const [message, setMessage] = useState('');
  const [loading, setLoading] = useState(false);

  async function loadRatings() {
    if (!user?.user_id) return;
    setLoading(true);
    setMessage('');

    try {
      const { data } = await api.get('/admin/performance-evaluations', {
        params: { user_id: user.user_id }
      });

      if (!data.success) {
        throw new Error(data.message || 'Unable to load performance ratings.');
      }

      setEvaluations(Array.isArray(data.evaluations) ? data.evaluations : []);
      setSummary(data.summary || {});
    } catch (err) {
      setMessage(getApiMessage(err, 'Unable to load performance ratings.'));
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadRatings().catch(() => {});
  }, [user?.user_id]);

  const exportHeaders = ['Employee', 'Department', 'Period', 'Review Date', 'Score', 'Rating', 'Growth Goals', 'Action Plan'];
  const rows = evaluations.map((row) => [
    `${row.emp_code || 'N/A'} - ${row.employee_name || 'Employee'}`,
    row.department || 'N/A',
    row.review_period || '-',
    row.review_date || '-',
    Number(row.overall_score || 0).toFixed(1),
    row.rating || '-',
    row.goals || '-',
    row.action_plan || '-'
  ]);

  function exportPerformance(format) {
    exportReport(
      format,
      'performance-growth-evaluation-ratings',
      'Growth Evaluation Ratings',
      exportHeaders,
      rows
    );
  }

  return (
    <>
      <section className="summary react-summary">
        <div className="card"><span>Employees Rated</span><strong>{summary.employeesWithRatings || 0}</strong></div>
        <div className="card"><span>Average Score</span><strong>{summary.averageScore === null || summary.averageScore === undefined ? '-' : Number(summary.averageScore).toFixed(1)}</strong></div>
        <div className="card"><span>Latest Rating</span><strong>{summary.latestRating || '-'}</strong></div>
      </section>
      <section className="table-section">
        <div className="table-header employee-mgmt-header">
          <div>
            <h3>Growth Evaluation Ratings</h3>
            <p>Latest employee rating from saved Growth Evaluation records.</p>
          </div>
          <div className="row-actions">
            <button type="button" className="btn secondary" onClick={loadRatings} disabled={loading}>
              {loading ? 'Refreshing...' : 'Refresh'}
            </button>
            <label className="export-dropdown-label">
              Export
              <select
                defaultValue=""
                onChange={(event) => {
                  if (!event.target.value) return;
                  exportPerformance(event.target.value);
                  event.target.value = '';
                }}
              >
                <option value="" disabled>Select format</option>
                <option value="csv">CSV</option>
                <option value="pdf">PDF</option>
                <option value="txt">Text</option>
              </select>
            </label>
          </div>
        </div>
        {message ? <p className="message">{message}</p> : null}
        <SimpleTable headers={exportHeaders} rows={rows} />
      </section>
    </>
  );
}

function CustomReportBuilder() {
  const reports = [
    {
      id: 'payroll-journal',
      title: 'Payroll Journal',
      category: 'Payroll',
      purpose: 'Shows each payroll run with gross pay, deductions, and net pay for audit and review.',
      route: 'payroll_journal.html',
      fields: 'Company, employee, gross pay, deductions, net pay',
      frequency: 'Per payroll run'
    },
    {
      id: 'gross-pay',
      title: 'Gross Pay',
      category: 'Payroll',
      purpose: 'Summarizes earnings before deductions are applied.',
      route: 'gross_pay.html',
      fields: 'Employee ID, employee name, company, gross pay',
      frequency: 'Per payroll run'
    },
    {
      id: 'net-pay',
      title: 'Net Pay',
      category: 'Payroll',
      purpose: 'Shows take-home pay after all deductions and contributions.',
      route: 'net_pay.html',
      fields: 'Employee ID, employee name, company, net pay',
      frequency: 'Per payroll run'
    },
    {
      id: 'payslip',
      title: 'Payslip',
      category: 'Payroll',
      purpose: 'Employee pay statement with earnings, deductions, and payout details.',
      route: 'payslip.html',
      fields: 'Employee, pay period, gross pay, deductions, net pay',
      frequency: 'Per payroll run'
    },
    {
      id: 'government-reports',
      title: 'Government Reports',
      category: 'Compliance',
      purpose: 'Provides BIR, SSS, PhilHealth, and Pag-IBIG export templates.',
      route: 'government_reports.html',
      fields: 'BIR 1601-C, BIR 2316, BIR 1604-C, SSS R3/R5, PhilHealth RF-1, Pag-IBIG MCRF',
      frequency: 'Monthly / Annual'
    },
    {
      id: 'reconciliation-details',
      title: 'Reconciliation Details',
      category: 'Payroll',
      purpose: 'Compares gross, deductions, and net pay totals for validation.',
      route: 'reconciliation_details.html',
      fields: 'Employee ID, gross, deductions, net, delta',
      frequency: 'Per payroll run'
    }
  ];
  const categories = ['All', 'Payroll', 'Compliance'];
  const [category, setCategory] = useState('All');
  const [selectedReportId, setSelectedReportId] = useState(reports[0].id);
  const selectedReport = reports.find((report) => report.id === selectedReportId) || reports[0];

  const rows = reports.filter((row) => category === 'All' || row.category === category);

  useEffect(() => {
    if (!rows.some((report) => report.id === selectedReportId)) {
      setSelectedReportId(rows[0]?.id || reports[0].id);
    }
  }, [category, rows, reports, selectedReportId]);

  function exportBuilder() {
    downloadCsv(
      'report-builder-template.csv',
      ['Report', 'Category', 'Purpose', 'Route', 'Fields', 'Frequency'],
      rows.map((row) => [row.title, row.category, row.purpose, row.route, row.fields, row.frequency])
    );
  }

  return (
    <section className="table-section">
      <h3>Report Builder</h3>
      <p style={{ marginTop: 0 }}>Use this module to select a payroll summary report, review its purpose, and export a template for the chosen report.</p>
      <div className="report-filter-grid">
        <label>
          Category
          <select value={category} onChange={(event) => setCategory(event.target.value)}>
            {categories.map((value) => <option key={value}>{value}</option>)}
          </select>
        </label>
        <label>
          Available Reports
          <select value={selectedReportId} onChange={(event) => setSelectedReportId(event.target.value)}>
            {rows.map((report) => <option key={report.id} value={report.id}>{report.title}</option>)}
          </select>
        </label>
        <label>
          Purpose
          <textarea value={selectedReport.purpose} readOnly rows={4} style={{ resize: 'none' }} />
        </label>
        <label>
          Open Report
          <input type="text" readOnly value={selectedReport.route} />
        </label>
        <div className="toolbar">
          <button type="button" className="btn" onClick={() => { window.location.href = selectedReport.route; }}>Open Report</button>
          <button type="button" className="btn secondary" onClick={exportBuilder}>Export Template</button>
        </div>
      </div>
      <SimpleTable headers={['Report', 'Category', 'Purpose', 'Route', 'Fields', 'Frequency']} rows={rows.map((row) => [row.title, row.category, row.purpose, row.route, row.fields, row.frequency])} />
    </section>
  );
}

function SecurityCenter() {
  const rows = [
    ['Sensitive Data Encryption', 'TIN, SSS, PhilHealth, Pag-IBIG, bank info', 'Ready for DB migration'],
    ['Backup and Restore', 'Scheduled backup, restore logs, backup status report', 'Configured workflow'],
    ['Payslip Email Distribution', 'Release payslips with employee notification', 'Needs SMTP credentials'],
    ['Push Notifications', 'Leave, payslip, and reminder alerts', 'Mobile app dependency']
  ];

  return (
    <>
      <section className="table-section">
        <h3>Role-Based Module Permissions</h3>
        <div className="permission-grid">
          {['Admin', 'HR', 'Employee'].map((role) => (
            <article key={role}>
              <h4>{role}</h4>
              {PERMISSIONS.map((permission) => (
                <label key={`${role}-${permission}`}>
                  <input type="checkbox" defaultChecked={role === 'Admin' || (role === 'HR' && permission !== 'Payroll computation') || (role === 'Employee' && ['Payslip release'].includes(permission))} />
                  {permission}
                </label>
              ))}
            </article>
          ))}
        </div>
      </section>
      <section className="table-section">
        <h3>Security, Backup, and Notification Readiness</h3>
        <SimpleTable headers={['Feature', 'Scope', 'Status']} rows={rows} />
      </section>
    </>
  );
}

function AnalyticsAndMobile() {
  const [analytics, setAnalytics] = useState(null);
  const [message, setMessage] = useState('');
  const [loading, setLoading] = useState(false);

  async function loadAnalytics() {
    setLoading(true);
    setMessage('');
    try {
      const { data } = await api.get('/ai-analytics');
      if (!data.success) {
        throw new Error(data.message || 'Unable to load AI analytics.');
      }
      setAnalytics(data);
    } catch (err) {
      setMessage(getApiMessage(err, 'Unable to load AI analytics.'));
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadAnalytics().catch(() => {});
  }, []);

  const summary = analytics?.summary || {};
  const otTrendRows = analytics
    ? [
        ...(analytics.overtimePatterns || []).map((row) => ({
          label: `${row.week_start || row.week_key}`,
          value: Number(row.total_hours || 0),
          group: row.department || 'N/A'
        })),
        {
          label: 'Forecast',
          value: Number(analytics.forecast?.nextWeekHours || 0),
          group: 'Next week'
        }
      ]
    : [];

  return (
    <>
      <section className="analytics-hero">
        <div>
          <span>Live Workforce Signals</span>
          <h3>AI Analytics</h3>
          <p>Tardiness, absence, turnover risk, overtime pressure, and next-week forecasting from live HRIS data.</p>
        </div>
        <button type="button" className="btn secondary" onClick={loadAnalytics} disabled={loading}>
          {loading ? 'Refreshing...' : 'Refresh Analytics'}
        </button>
      </section>

      <section className="analytics-metric-grid">
        <AnimatedMetricCard label="Tardiness Rate" value={`${Number(summary.tardinessRate || 0).toFixed(2)}%`} detail={`${Number(summary.lateDays || 0)} late signal(s)`} tone="blue" />
        <AnimatedMetricCard label="Absence Rate" value={`${Number(summary.absenceRate || 0).toFixed(2)}%`} detail={`${Number(summary.absentDays || 0)} absence signal(s)`} tone="cyan" />
        <AnimatedMetricCard label="High Turnover Risks" value={summary.highTurnoverRisks || 0} detail="Heuristic risk model" tone="violet" />
        <AnimatedMetricCard label="Next Week OT Forecast" value={Number(summary.nextWeekOtForecast || 0).toFixed(2)} detail={`${analytics?.forecast?.direction || 'Stable'} trend`} tone="green" />
      </section>

      {message ? <p className="message">{message}</p> : null}
      {!analytics && !message ? <section className="table-section"><p className="muted">Loading analytics...</p></section> : null}

      {analytics ? (
        <>
          <section className="analytics-panel-grid">
            <AnimatedBarChart
              title="Tardiness Patterns"
              subtitle="Late time-in signals by day, last 30 days"
              rows={(analytics.tardinessPatterns || []).map((row) => ({ label: row.day_name, value: Number(row.late_count || 0) }))}
              empty="No tardiness signals found in the last 30 days."
            />
            <AnimatedBarChart
              title="Absence Patterns"
              subtitle="Absence signals by department, last 30 weekdays"
              rows={(analytics.absencePatterns || []).map((row) => ({ label: row.department || 'N/A', value: Number(row.absence_days || 0) }))}
              empty="No absence signals found in the last 30 weekdays."
            />
          </section>

          <section className="table-section">
            <h3>Turnover Risk Spotlight</h3>
            <RiskRadar rows={analytics.turnoverRisks || []} />
          </section>

          <section className="table-section">
            <h3>Employee Turnover Prediction</h3>
            <SimpleTable
              headers={['Employee', 'Department', 'Risk', 'Score', 'Signals']}
              rows={(analytics.turnoverRisks || []).map((row) => [
                `${row.emp_code || 'N/A'} - ${row.employee_name || 'Employee'}`,
                row.department || 'N/A',
                row.risk_band,
                Number(row.risk_score || 0).toFixed(1),
                row.insight
              ])}
            />
          </section>

          <section className="table-section">
            <h3>OT Patterns and Forecasting</h3>
            <ForecastLineChart rows={otTrendRows} forecast={analytics.forecast || {}} />
            <AnimatedBarChart
              title="Approved OT by Week and Department"
              subtitle="Moving bars show relative overtime pressure"
              rows={(analytics.overtimePatterns || []).map((row) => ({
                label: `${row.week_start || row.week_key} - ${row.department || 'N/A'}`,
                value: Number(row.total_hours || 0),
                suffix: 'h'
              }))}
              empty="No approved overtime requests found for the last 8 weeks."
            />
          </section>
        </>
      ) : null}
    </>
  );
}

function AnimatedMetricCard({ label, value, detail, tone }) {
  return (
    <article className={`analytics-metric-card ${tone || 'blue'}`}>
      <span>{label}</span>
      <strong>{value}</strong>
      <small>{detail}</small>
      <i />
    </article>
  );
}

function AnimatedBarChart({ title, subtitle, rows, empty }) {
  const max = Math.max(...(rows || []).map((row) => Number(row.value || 0)), 1);

  return (
    <article className="analytics-chart-card">
      <div className="analytics-chart-header">
        <div>
          <h4>{title}</h4>
          <p>{subtitle}</p>
        </div>
      </div>
      <div className="analytics-bars">
        {!rows?.length ? <p className="muted">{empty}</p> : null}
        {(rows || []).map((row, index) => {
          const width = Math.max((Number(row.value || 0) / max) * 100, 4);
          return (
            <div className="analytics-bar-row" key={`${row.label}-${index}`} style={{ '--bar-width': `${width}%`, '--bar-delay': `${index * 80}ms` }}>
              <span>{row.label}</span>
              <b><i /></b>
              <strong>{Number(row.value || 0).toFixed(row.suffix ? 2 : 0)}{row.suffix || ''}</strong>
            </div>
          );
        })}
      </div>
    </article>
  );
}

function ForecastLineChart({ rows, forecast }) {
  const values = (rows || []).map((row) => Number(row.value || 0));
  const max = Math.max(...values, 1);
  const points = (rows || []).map((row, index) => {
    const x = rows.length <= 1 ? 50 : (index / (rows.length - 1)) * 100;
    const y = 90 - ((Number(row.value || 0) / max) * 70);
    return `${x},${y}`;
  }).join(' ');

  return (
    <article className="analytics-chart-card forecast-card">
      <div className="analytics-chart-header">
        <div>
          <h4>Overtime Forecast Curve</h4>
          <p>Weekly approved OT plus projected next-week demand</p>
        </div>
        <strong>{forecast.direction || 'Stable'}</strong>
      </div>
      <svg className="analytics-line-chart" viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Overtime forecast line chart">
        <defs>
          <linearGradient id="analyticsLineGradient" x1="0" x2="1">
            <stop offset="0%" stopColor="#0a66d9" />
            <stop offset="55%" stopColor="#28c8ff" />
            <stop offset="100%" stopColor="#7c4dff" />
          </linearGradient>
        </defs>
        <polyline className="analytics-grid-line" points="0,90 100,90" />
        <polyline className="analytics-grid-line" points="0,55 100,55" />
        <polyline className="analytics-grid-line" points="0,20 100,20" />
        <polyline className="analytics-forecast-line" points={points || '0,90 100,90'} />
        {(rows || []).map((row, index) => {
          const x = rows.length <= 1 ? 50 : (index / (rows.length - 1)) * 100;
          const y = 90 - ((Number(row.value || 0) / max) * 70);
          return <circle key={`${row.label}-${index}`} className={row.label === 'Forecast' ? 'forecast-dot' : ''} cx={x} cy={y} r="1.7" />;
        })}
      </svg>
      <div className="forecast-stats">
        <span>Current <strong>{Number(forecast.currentWeekHours || 0).toFixed(2)}h</strong></span>
        <span>Average <strong>{Number(forecast.weeklyAverage || 0).toFixed(2)}h</strong></span>
        <span>Forecast <strong>{Number(forecast.nextWeekHours || 0).toFixed(2)}h</strong></span>
      </div>
    </article>
  );
}

function RiskRadar({ rows }) {
  const topRows = (rows || []).slice(0, 5);

  return (
    <div className="risk-radar">
      {topRows.length === 0 ? <p className="muted">No turnover risk signals available.</p> : null}
      {topRows.map((row, index) => {
        const score = Math.min(100, Number(row.risk_score || 0));
        return (
          <article key={`${row.emp_code}-${index}`} style={{ '--risk-score': `${score}%`, '--risk-delay': `${index * 100}ms` }}>
            <div className="risk-orbit"><i /></div>
            <div>
              <strong>{row.employee_name || 'Employee'}</strong>
              <span>{row.risk_band} risk · {score.toFixed(1)}</span>
              <small>{row.insight}</small>
            </div>
          </article>
        );
      })}
    </div>
  );
}

function SimpleTable({ headers, rows }) {
  return (
    <div className="table-scroll">
      <table>
        <thead>
          <tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr>
        </thead>
        <tbody>
          {rows.length === 0 ? <tr><td colSpan={headers.length}>No rows found.</td></tr> : null}
          {rows.map((row, index) => (
            <tr key={`${row.join('-')}-${index}`}>
              {row.map((cell, cellIndex) => <td key={`${cell}-${cellIndex}`}>{cell}</td>)}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
