function csvCell(value) {
  return `"${String(value ?? '').replace(/"/g, '""')}"`;
}

export const REPORT_COMPANY_NAME_FALLBACK = 'Astreablue Intelligence Inc.';

export function getReportCompanyProfile() {
  if (typeof window === 'undefined') return { company_name: REPORT_COMPANY_NAME_FALLBACK };
  try {
    const saved = JSON.parse(localStorage.getItem('sys_company_profile') || '{}');
    return { ...saved, company_name: saved.company_name || localStorage.getItem('sys_company_name') || REPORT_COMPANY_NAME_FALLBACK };
  } catch {
    return { company_name: localStorage.getItem('sys_company_name') || REPORT_COMPANY_NAME_FALLBACK };
  }
}

export function getReportCompanyName() {
  return getReportCompanyProfile().company_name;
}

// Backward-compat alias used internally
const REPORT_COMPANY_NAME = getReportCompanyName;

export function getReportGeneratedBy() {
  if (typeof window === 'undefined') return 'System User';
  return (
    sessionStorage.getItem('admin_name') ||
    sessionStorage.getItem('full_name') ||
    sessionStorage.getItem('username') ||
    sessionStorage.getItem('user_id') ||
    'System User'
  );
}

export function getReportGeneratedAt() {
  return new Date().toLocaleString('en-PH', {
    month: 'short',
    day: '2-digit',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: true
  });
}

export function getReportMetadata(title, generatedAt = getReportGeneratedAt(), generatedBy = getReportGeneratedBy()) {
  const company = getReportCompanyProfile();
  return {
    companyName: company.company_name || REPORT_COMPANY_NAME(),
    companyAddress: company.address || '',
    companyTin: company.tin || '',
    companyRegistrationNo: company.registration_no || '',
    companyEmail: company.email || '',
    companyPhone: company.phone || '',
    companyWebsite: company.website || '',
    companyIndustry: company.industry || '',
    companyFoundedYear: company.founded_year || '',
    title: title || 'Report',
    generatedAt,
    generatedBy,
    signatories: ['Prepared By:', 'Checked By:', 'Verified By:', 'Approved By:']
  };
}

function downloadBlob(filename, blob) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.rel = 'noopener';
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function rowsToDelimited(headers, rows, delimiter) {
  return [headers, ...rows]
    .map((row) => row.map((cell) => delimiter === ',' ? csvCell(cell) : String(cell ?? '')).join(delimiter))
    .join('\n');
}

function reportRowsToDelimited(title, headers, rows, delimiter) {
  const meta = getReportMetadata(title);
  const label = delimiter === ',' ? (value) => csvCell(value) : (value) => String(value ?? '');
  const line = (values) => values.map(label).join(delimiter);

  return [
    line([meta.companyName]),
    ...(meta.companyAddress ? [line([meta.companyAddress])] : []),
    ...(meta.companyTin ? [line(['TIN', meta.companyTin])] : []),
    ...(meta.companyRegistrationNo ? [line(['Registration No.', meta.companyRegistrationNo])] : []),
    ...((meta.companyEmail || meta.companyPhone || meta.companyWebsite) ? [line(['Contact', [meta.companyEmail, meta.companyPhone, meta.companyWebsite].filter(Boolean).join(' | ')])] : []),
    line([meta.title]),
    line(['Generated', meta.generatedAt]),
    line(['Generated By', meta.generatedBy]),
    '',
    rowsToDelimited(headers, rows, delimiter),
    '',
    ...meta.signatories.map((item) => line([item]))
  ].join('\n');
}

function pdfEscape(value) {
  return String(value ?? '')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');
}

function makePdf(title, headers, rows) {
  const pageWidth = 842;
  const pageHeight = 595;
  const margin = 28;
  const tableWidth = pageWidth - margin * 2;
  const headerHeight = 22;
  const rowLineHeight = 9;
  const cellPadding = 4;
  const bodyFontSize = 7;
  const maxCellLines = 4;
  const meta = getReportMetadata(title);

  function textWidth(text, fontSize = bodyFontSize) {
    return String(text ?? '').length * fontSize * 0.52;
  }

  function columnWeight(header) {
    const text = String(header || '').toLowerCase();
    if (text.includes('reason')) return 2.4;
    if (text.includes('employee name')) return 1.7;
    if (text.includes('submitted') || text.includes('updated')) return 1.45;
    if (text.includes('leave type')) return 1.25;
    if (text.includes('start') || text.includes('end') || text === 'date') return 1.05;
    if (text.includes('status') || text.includes('hours') || text.includes('days') || text.includes('id')) return 0.8;
    return 1;
  }

  function columnWidths() {
    const weights = headers.map(columnWeight);
    const total = weights.reduce((sum, value) => sum + value, 0) || 1;
    return weights.map((value) => (value / total) * tableWidth);
  }

  function wrapCell(value, width) {
    const maxChars = Math.max(6, Math.floor((width - cellPadding * 2) / (bodyFontSize * 0.52)));
    const words = String(value ?? '').replace(/\s+/g, ' ').trim().split(' ').filter(Boolean);
    const lines = [];

    if (!words.length) return [''];

    const queue = [...words];
    while (queue.length) {
      const word = queue.shift();
      const last = lines[lines.length - 1] || '';
      const chunk = word.length > maxChars ? word.slice(0, maxChars) : word;

      if (word.length > maxChars) {
        queue.unshift(word.slice(maxChars));
      }

      if (!last) {
        lines.push(chunk);
        continue;
      }

      if (`${last} ${chunk}`.length <= maxChars) {
        lines[lines.length - 1] = `${last} ${chunk}`;
      } else {
        lines.push(chunk);
      }
    }

    if (lines.length > maxCellLines) {
      const kept = lines.slice(0, maxCellLines);
      kept[maxCellLines - 1] = `${kept[maxCellLines - 1].slice(0, Math.max(0, maxChars - 3))}...`;
      return kept;
    }

    return lines;
  }

  function drawText(text, x, y, { font = 'F1', size = bodyFontSize } = {}) {
    return `BT /${font} ${size} Tf ${x.toFixed(2)} ${y.toFixed(2)} Td (${pdfEscape(text)}) Tj ET`;
  }

  function drawCenteredText(text, y, { font = 'F1', size = bodyFontSize } = {}) {
    const x = (pageWidth - textWidth(text, size)) / 2;
    return drawText(text, x, y, { font, size });
  }

  function drawCellText(lines, x, topY, width, height, options = {}) {
    const font = options.bold ? 'F2' : 'F1';
    const size = options.size || bodyFontSize;
    const startY = topY - cellPadding - size;
    return lines.map((line, index) => {
      let display = String(line ?? '');
      const maxWidth = width - cellPadding * 2;
      while (textWidth(display, size) > maxWidth && display.length > 3) {
        display = `${display.slice(0, -4)}...`;
      }
      return drawText(display, x + cellPadding, startY - index * rowLineHeight, { font, size });
    }).join('\n');
  }

  const widths = columnWidths();
  const pages = [];
  let commands = [];
  let currentPage = 0;
  let y = pageHeight - margin;

  function startPage() {
    currentPage += 1;
    commands = [];
    y = pageHeight - margin;

    commands.push('0.08 0.15 0.28 rg');
    commands.push(drawCenteredText(meta.companyName, y - 1, { font: 'F2', size: 14 }));
    const companyLine = [meta.companyAddress, meta.companyTin ? `TIN: ${meta.companyTin}` : ''].filter(Boolean).join(' | ');
    if (companyLine) commands.push(drawCenteredText(companyLine, y - 15, { size: 7 }));
    commands.push(drawCenteredText(meta.title, y - (companyLine ? 29 : 18), { font: 'F2', size: 11 }));
    commands.push('0.38 0.44 0.53 rg');
    commands.push(drawCenteredText(`Generated: ${meta.generatedAt} | Generated By: ${meta.generatedBy} | Rows: ${rows.length}`, y - (companyLine ? 44 : 34), { size: 8 }));
    y -= companyLine ? 66 : 56;

    commands.push('0.91 0.95 1.00 rg');
    commands.push(`${margin} ${(y - headerHeight).toFixed(2)} ${tableWidth.toFixed(2)} ${headerHeight} re f`);
    commands.push('0.62 0.68 0.76 RG');
    commands.push(`${margin} ${(y - headerHeight).toFixed(2)} ${tableWidth.toFixed(2)} ${headerHeight} re S`);

    let x = margin;
    headers.forEach((header, index) => {
      commands.push('0.08 0.15 0.28 rg');
      commands.push(drawCellText(wrapCell(header, widths[index]), x, y, widths[index], headerHeight, { bold: true, size: 7 }));
      if (index > 0) {
        commands.push('0.78 0.82 0.88 RG');
        commands.push(`${x.toFixed(2)} ${(y - headerHeight).toFixed(2)} m ${x.toFixed(2)} ${y.toFixed(2)} l S`);
      }
      x += widths[index];
    });
    y -= headerHeight;
  }

  function finishPage() {
    commands.push('0.45 0.50 0.58 rg');
    commands.push(drawText(`Page ${currentPage}`, pageWidth - margin - 34, margin - 8, { size: 8 }));
    pages.push(commands.join('\n'));
  }

  startPage();

  rows.forEach((row, rowIndex) => {
    const wrappedCells = headers.map((_, index) => wrapCell(row[index], widths[index]));
    const rowHeight = Math.max(20, Math.max(...wrappedCells.map((cell) => cell.length)) * rowLineHeight + cellPadding * 2 + 2);

    if (y - rowHeight < margin + 12) {
      finishPage();
      startPage();
    }

    if (rowIndex % 2 === 0) {
      commands.push('0.98 0.99 1.00 rg');
      commands.push(`${margin} ${(y - rowHeight).toFixed(2)} ${tableWidth.toFixed(2)} ${rowHeight.toFixed(2)} re f`);
    }

    commands.push('0.86 0.89 0.94 RG');
    commands.push(`${margin} ${(y - rowHeight).toFixed(2)} ${tableWidth.toFixed(2)} ${rowHeight.toFixed(2)} re S`);

    let x = margin;
    wrappedCells.forEach((cell, index) => {
      commands.push('0.10 0.14 0.20 rg');
      commands.push(drawCellText(cell, x, y, widths[index], rowHeight));
      if (index > 0) {
        commands.push('0.90 0.92 0.95 RG');
        commands.push(`${x.toFixed(2)} ${(y - rowHeight).toFixed(2)} m ${x.toFixed(2)} ${y.toFixed(2)} l S`);
      }
      x += widths[index];
    });

    y -= rowHeight;
  });

  if (!rows.length) {
    commands.push('0.35 0.40 0.48 rg');
    commands.push(drawText('No rows available for this report.', margin, y - 20, { size: 10 }));
  }

  const signatoryHeight = 64;
  if (y - signatoryHeight < margin + 12) {
    finishPage();
    startPage();
  }

  y -= 26;
  const signatureWidth = tableWidth / 4;
  meta.signatories.forEach((label, index) => {
    const x = margin + index * signatureWidth;
    commands.push('0.20 0.24 0.30 rg');
    commands.push(drawText(label, x, y, { font: 'F2', size: 8 }));
    commands.push('0.55 0.60 0.67 RG');
    commands.push(`${x.toFixed(2)} ${(y - 24).toFixed(2)} m ${(x + signatureWidth - 18).toFixed(2)} ${(y - 24).toFixed(2)} l S`);
  });

  finishPage();

  const objects = [];
  const addObject = (content) => {
    objects.push(content);
    return objects.length;
  };

  const fontId = addObject('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
  const boldFontId = addObject('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');
  const pageIds = [];
  const contentIds = [];

  pages.forEach((stream) => {
    const contentId = addObject(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);
    contentIds.push(contentId);
  });

  const pagesId = objects.length + pages.length + 1;
  contentIds.forEach((contentId) => {
    pageIds.push(addObject(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F1 ${fontId} 0 R /F2 ${boldFontId} 0 R >> >> /Contents ${contentId} 0 R >>`));
  });

  const actualPagesId = addObject(`<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(' ')}] /Count ${pageIds.length} >>`);
  const catalogId = addObject(`<< /Type /Catalog /Pages ${actualPagesId} 0 R >>`);

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root ${catalogId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return pdf;
}

export function exportReport(format, filenameBase, title, headers, rows) {
  const normalized = String(format || 'csv').toLowerCase();
  const safeBase = filenameBase || 'report';

  if (normalized === 'txt') {
    const text = reportRowsToDelimited(title, headers, rows, '\t');
    downloadBlob(`${safeBase}.txt`, new Blob([text], { type: 'text/plain;charset=utf-8;' }));
    return;
  }

  if (normalized === 'pdf') {
    const pdf = makePdf(title, headers, rows);
    downloadBlob(`${safeBase}.pdf`, new Blob([pdf], { type: 'application/pdf' }));
    return;
  }

  const csv = reportRowsToDelimited(title, headers, rows, ',');
  downloadBlob(`${safeBase}.csv`, new Blob([`\ufeff${csv}`], { type: 'text/csv;charset=utf-8;' }));
}
